import { NextRequest, NextResponse } from "next/server";
import { GIFEncoder, quantize, applyPalette } from "gifenc";
import jpeg from "jpeg-js";
import { PNG } from "pngjs";

export const dynamic = "force-dynamic";
export const maxDuration = 120;

const MAX_FRAMES = 8;
const MAX_DIM = 480;
const MAX_BYTES = 5 * 1024 * 1024;
const PRIVATE_HOST =
  /^(localhost|127\.|0\.0\.0\.0|::1|10\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.|169\.254\.)/i;

async function loadFrame(src: string): Promise<Buffer> {
  if (src.startsWith("data:")) {
    const m = /^data:image\/(png|jpeg|jpg|webp);base64,(.+)$/i.exec(src);
    if (!m) throw new Error("unsupported data uri (use png/jpeg base64)");
    const buf = Buffer.from(m[2], "base64");
    if (buf.length > MAX_BYTES) throw new Error("frame too large (5MB max)");
    return buf;
  }
  let u: URL;
  try {
    u = new URL(src);
  } catch {
    throw new Error(`invalid frame url: ${src.slice(0, 60)}`);
  }
  if (u.protocol !== "http:" && u.protocol !== "https:") throw new Error("frame urls must be http(s)");
  if (PRIVATE_HOST.test(u.hostname)) throw new Error("frame url host not allowed");
  const res = await fetch(u.toString(), { signal: AbortSignal.timeout(25_000) });
  if (!res.ok) throw new Error(`frame download failed: HTTP ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  if (buf.length > MAX_BYTES) throw new Error("frame too large (5MB max)");
  return buf;
}

function decode(buf: Buffer): { data: Uint8Array; width: number; height: number } {
  // JPEG (pollinations default)
  if (buf[0] === 0xff && buf[1] === 0xd8) {
    const img = jpeg.decode(buf, { useTArray: true, maxMemoryUsageInMB: 256 });
    return { data: img.data as unknown as Uint8Array, width: img.width, height: img.height };
  }
  // PNG
  if (buf[0] === 0x89 && buf[1] === 0x50) {
    const img = PNG.sync.read(buf);
    return { data: new Uint8Array(img.data), width: img.width, height: img.height };
  }
  throw new Error("unsupported frame format (need jpeg or png — pollinations returns jpeg)");
}

function fit(
  frame: { data: Uint8Array; width: number; height: number },
  w: number,
  h: number
): Uint8Array {
  if (frame.width === w && frame.height === h) return frame.data;
  // nearest-neighbour — fast, good enough for storyboard frames
  const out = new Uint8Array(w * h * 4);
  for (let y = 0; y < h; y++) {
    const sy = Math.min(frame.height - 1, Math.floor((y * frame.height) / h));
    for (let x = 0; x < w; x++) {
      const sx = Math.min(frame.width - 1, Math.floor((x * frame.width) / w));
      const si = (sy * frame.width + sx) * 4;
      const di = (y * w + x) * 4;
      out[di] = frame.data[si];
      out[di + 1] = frame.data[si + 1];
      out[di + 2] = frame.data[si + 2];
      out[di + 3] = frame.data[si + 3];
    }
  }
  return out;
}

/**
 * POST {frames: string[], fps?, loop?} → animated GIF (data URI).
 * Frames are image URLs or data: URIs — generated by the image skill, stitched here.
 */
export async function POST(req: NextRequest) {
  let body: any;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "invalid JSON body" }, { status: 400 });
  }
  const frames = Array.isArray(body.frames) ? body.frames.slice(0, MAX_FRAMES) : [];
  if (frames.length < 2)
    return NextResponse.json({ error: `need at least 2 frames (got ${frames.length})` }, { status: 400 });
  const fps = Math.min(Math.max(Number(body.fps) || 4, 1), 12);
  const delay = Math.round(1000 / fps);

  try {
    const bufs = await Promise.all(frames.map((f: string) => loadFrame(String(f))));
    const decoded = bufs.map(decode);

    let w = Math.min(MAX_DIM, Math.max(...decoded.map((d) => d.width)));
    let h = Math.round((decoded[0].height / decoded[0].width) * w);
    if (h % 2) h += 1;

    const gif = GIFEncoder();
    for (const d of decoded) {
      const rgba = fit(d, w, h);
      const palette = quantize(rgba, 256);
      const index = applyPalette(rgba, palette);
      gif.writeFrame(index, w, h, { palette, delay });
    }
    gif.finish();
    const bytes = Buffer.from(gif.bytes());
    const gif64 = bytes.toString("base64");

    return NextResponse.json({
      gif: `data:image/gif;base64,${gif64}`,
      width: w,
      height: h,
      frames: decoded.length,
      fps,
      bytes: bytes.length,
    });
  } catch (e: any) {
    return NextResponse.json(
      { error: `video build failed: ${e?.message || "decode error"}` },
      { status: 422 }
    );
  }
}
